# Generated by Django 2.2 on 2020-12-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(max_length=64)),
                ('Title', models.CharField(max_length=128)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
